Vagrant.configure('2') do |config|
  ## Frontend webserver
  config.vm.define 'webserver' do |node|
    node.vm.box = 'coreos'
    node.vm.hostname = 'webserver'
    node.vm.box_check_update = false
    node.vm.network 'private_network', ip: '192.168.56.3', adapter: 2
    node.vm.network 'public_network', adapter: 3, bridge: 'wlan0'
    node.vm.synced_folder './', '/vagrant', disabled: false
    node.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = '2048'
      vb.cpus = 1
    end
    node.vm.provision 'shell', path: 'install_webserver.sh'
  end

  ## Backend Database
  config.vm.define 'database' do |node|
    node.vm.box = 'coreos'
    node.vm.hostname = 'database'
    node.vm.box_check_update = false
    node.vm.network 'private_network', ip: '192.168.56.2', adapter: 2
    node.vm.network 'public_network', adapter: 3, bridge: 'wlan0'
    node.vm.synced_folder './', '/vagrant', disabled: false
    node.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = '1048'
      vb.cpus = 1
    end
    node.vm.provision 'shell', path: 'install_database.sh'
  end
end
