servers = [
  {
    :hostname => "master",
    :ip=> "192.168.56.10",
    :ram => 4096,
    :cpu => 2,
    :box=>"cloud-image/debian-13"},
  {
    :hostname => "worker1",
    :ip=> "192.168.56.11",
    :ram => 1024, :cpu => 1,
    :box=>"cloud-image/debian-13"}
]
Vagrant.configure("2") do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      #box
      node.vm.box = machine[:box]
      node.vm.box_version = "20260220.2394.0"
      node.vm.box_check_update = false
      node.vm.hostname = machine[:hostname]
      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end

      #network
      node.vm.network "private_network", ip: machine[:ip], adapter: 2

      #sync folder
      node.vm.synced_folder "./data", "/vagrant", disabled: false
      node.vm.provision "shell", path: "install_docker.sh"
      node.vm.provision "shell", path: "install_k8s.sh"
    end
  end
end
