Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.3", adapter: 2
  config.vm.network "public_network", adapter: 3, bridge: "wlan0"

  config.vm.synced_folder "./", "/vagrant_data", disabled: false

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
     vb.memory = "1024"
   end
  config.vm.provision "shell", path: "apache_web.sh"

end
